# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class OperationKind(StrEnum):
    """
    The 11 v0 operation kinds (6 primary + 5 modifier, carried from Maquette).
    """

    box = 'box'
    cylinder = 'cylinder'
    sphere = 'sphere'
    extrude = 'extrude'
    revolve = 'revolve'
    loft = 'loft'
    hole = 'hole'
    fillet = 'fillet'
    chamfer = 'chamfer'
    shell = 'shell'
    pattern = 'pattern'


class Axis(StrEnum):
    field_X = '+X'
    field_X_1 = '-X'
    field_Y = '+Y'
    field_Y_1 = '-Y'
    field_Z = '+Z'
    field_Z_1 = '-Z'


class SurfaceType(StrEnum):
    planar = 'planar'
    cylindrical = 'cylindrical'
    spherical = 'spherical'
    conical = 'conical'
    toroidal = 'toroidal'
    freeform = 'freeform'


class Point3(RootModel[list[float]]):
    """
    World-space point [x, y, z] in mm.
    """

    root: list[float] = Field(
        ...,
        description='World-space point [x, y, z] in mm.',
        max_length=3,
        min_length=3,
        title='Point3',
    )


class Unit(StrEnum):
    mm = 'mm'
    cm = 'cm'
    m = 'm'
    in_ = 'in'


class Parameter(BaseModel):
    """
    A named dimensioned scalar (carried from Maquette; referenceable in extras).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    value: float
    unit: Unit


class From(StrEnum):
    user = 'user'
    assistant = 'assistant'


class ConversationTurn(BaseModel):
    """
    A single exchange in a clarification thread.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    from_: From = Field(..., alias='from')
    text: str
    at: AwareDatetime


class FinderPredicate1(BaseModel):
    """
    A re-derivable geometric predicate identifying a face/edge/vertex across replay (ADR-0008). ANDed within a Selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['plane_normal']
    axis: Axis


class FinderPredicate2(BaseModel):
    """
    A re-derivable geometric predicate identifying a face/edge/vertex across replay (ADR-0008). ANDed within a Selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['contains_point']
    point_xyz: Point3
    tol_mm: float


class FinderPredicate3(BaseModel):
    """
    A re-derivable geometric predicate identifying a face/edge/vertex across replay (ADR-0008). ANDed within a Selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['surface_type']
    value: SurfaceType


class FinderPredicate4(BaseModel):
    """
    A re-derivable geometric predicate identifying a face/edge/vertex across replay (ADR-0008). ANDed within a Selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['centroid_near']
    point_xyz: Point3
    tol_mm: float


class FinderPredicate5(BaseModel):
    """
    A re-derivable geometric predicate identifying a face/edge/vertex across replay (ADR-0008). ANDed within a Selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['of_feature']
    op_id: str


class FinderPredicate6(BaseModel):
    """
    A re-derivable geometric predicate identifying a face/edge/vertex across replay (ADR-0008). ANDed within a Selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['area_near']
    area_mm2: float
    tol: float


class FinderPredicate7(BaseModel):
    """
    A re-derivable geometric predicate identifying a face/edge/vertex across replay (ADR-0008). ANDed within a Selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['edges_count']
    count: int


class FinderPredicate(
    RootModel[
        FinderPredicate1
        | FinderPredicate2
        | FinderPredicate3
        | FinderPredicate4
        | FinderPredicate5
        | FinderPredicate6
        | FinderPredicate7
    ]
):
    root: (
        FinderPredicate1
        | FinderPredicate2
        | FinderPredicate3
        | FinderPredicate4
        | FinderPredicate5
        | FinderPredicate6
        | FinderPredicate7
    ) = Field(
        ...,
        description='A re-derivable geometric predicate identifying a face/edge/vertex across replay (ADR-0008). ANDed within a Selection.',
        title='FinderPredicate',
    )


class Target(StrEnum):
    face = 'face'
    edge = 'edge'
    vertex = 'vertex'


class Selection(BaseModel):
    """
    Identifies a face/edge/vertex such that identity survives history replay (ADR-0008).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    target: Target
    point_xyz: Point3
    finder: list[FinderPredicate] = Field(..., min_length=1)
    face_id_at_capture: int | None = None


class Operation(BaseModel):
    """
    A single user-driven CAD action appended to the document history.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., description='UUID, stable across sessions.')
    kind: OperationKind
    params: dict[str, float | str | bool]
    selection: Selection | None = None
    prompt_text: str
    conversation: list[ConversationTurn]
    created_at: AwareDatetime


class ClarifyingQuestion(BaseModel):
    """
    The planner's request for disambiguation (F7) when a prompt is ambiguous.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    question: str
    attempt: int


class MsgPlan(BaseModel):
    """
    FE->BE: submit a prompt (+ optional selection context) for planning.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['plan']
    prompt_text: str
    selection: Selection | None = None


class MsgApplyOp(BaseModel):
    """
    FE->BE: apply a structured operation directly (no planning).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['applyOp']
    operation: Operation


class MsgCancel(BaseModel):
    """
    FE->BE: cancel the in-flight LLM/executor work (F17).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['cancel']


class MsgRebuild(BaseModel):
    """
    FE->BE: replay the document history and re-stream the mesh.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['rebuild']


class MsgExportStep(BaseModel):
    """
    FE->BE: export the current solid to a STEP file.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['exportStep']
    path: str | None = None


class MsgReady(BaseModel):
    """
    BE->FE: backend is up and accepting messages (F15).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['ready']
    schema_version: int


class MsgProgress(BaseModel):
    """
    BE->FE: progress update for a long-running operation.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['progress']
    stage: str
    message: str | None = None


class MsgOp(BaseModel):
    """
    BE->FE: the structured operation the planner produced and applied.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['op']
    operation: Operation


class MsgConversationTurn(BaseModel):
    """
    Either direction: a clarification turn (assistant question or user reply, F7).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['conversationTurn']
    turn: ConversationTurn
    question: ClarifyingQuestion | None = None


class MsgError(BaseModel):
    """
    BE->FE: a structured error (F21). Never a raw Python traceback.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    code: str
    message: str
    where: str | None = None


class MsgMeshFrame(BaseModel):
    """
    BE->FE: the JSON envelope that immediately precedes a binary mesh frame (F20). The binary buffers (vertices/normals/indices/face_tag_per_triangle/edge_tag_per_segment) follow as the next WS binary message.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['meshFrame']
    version: int
    vertex_count: int
    triangle_count: int
    edge_segment_count: int
    face_id_to_finder_hint: dict[str, Selection] = Field(
        ...,
        description='Map of (stringified u32 face id) -> Selection, for the FE click->selection flow.',
    )


class MsgNewDoc(BaseModel):
    """
    FE->BE: start a new empty document (F10).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['newDoc']


class MsgOpen(BaseModel):
    """
    FE->BE: open a .touch file by name from the project dir; the model is rebuilt by replaying its history (F10).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['open']
    name: str


class MsgSave(BaseModel):
    """
    FE->BE: save the current document as a .touch file (by name) under the project dir (F10).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['save']
    name: str


class MsgListFiles(BaseModel):
    """
    FE->BE: list the .touch files in the project dir (for the explorer).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['listFiles']


class MsgUndo(BaseModel):
    """
    FE->BE: step back one operation in the history (F9).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['undo']


class MsgRedo(BaseModel):
    """
    FE->BE: re-apply the last undone operation (F9).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['redo']


class MsgFileList(BaseModel):
    """
    BE->FE: the .touch files available in the project dir.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['fileList']
    files: list[str]


class MsgDocument(BaseModel):
    """
    BE->FE: a snapshot of the current document for the FE mirror — history, name, dirty + undo/redo availability (F8/F9/F10).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['document']
    name: str
    history: list[Operation]
    dirty: bool
    can_undo: bool
    can_redo: bool


class DirEntry(BaseModel):
    """
    One entry in a workspace directory listing.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    is_dir: bool


class MsgOpenFolder(BaseModel):
    """
    FE->BE: set the workspace root to this folder path (ADR-0010); the backend replies with the root `dir` listing.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['openFolder']
    path: str


class MsgListDir(BaseModel):
    """
    FE->BE: list a directory within the workspace (lazy expand); path is workspace-relative ("" = root).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['listDir']
    path: str


class MsgOpenPart(BaseModel):
    """
    FE->BE: open a .touch part by workspace-relative path; the model is rebuilt by replaying its history (F10).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['openPart']
    path: str


class MsgSavePart(BaseModel):
    """
    FE->BE: save the active document to a .touch part at this workspace-relative path (F10).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['savePart']
    path: str


class MsgNewPart(BaseModel):
    """
    FE->BE: create an empty .touch part at this workspace-relative path and open it.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['newPart']
    path: str


class MsgRenamePart(BaseModel):
    """
    FE->BE: rename/move a workspace entry from `path` to `to_path` (both workspace-relative).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['renamePart']
    path: str
    to_path: str


class MsgRemovePart(BaseModel):
    """
    FE->BE: delete a workspace entry at this workspace-relative path.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['removePart']
    path: str


class MsgDir(BaseModel):
    """
    BE->FE: a directory listing within the workspace (lazy per-folder).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['dir']
    path: str
    entries: list[DirEntry]


class Message(
    RootModel[
        MsgPlan
        | MsgApplyOp
        | MsgCancel
        | MsgRebuild
        | MsgExportStep
        | MsgReady
        | MsgProgress
        | MsgOp
        | MsgConversationTurn
        | MsgError
        | MsgMeshFrame
        | MsgNewDoc
        | MsgOpen
        | MsgSave
        | MsgListFiles
        | MsgUndo
        | MsgRedo
        | MsgFileList
        | MsgDocument
        | MsgOpenFolder
        | MsgListDir
        | MsgOpenPart
        | MsgSavePart
        | MsgNewPart
        | MsgRenamePart
        | MsgRemovePart
        | MsgDir
    ]
):
    root: (
        MsgPlan
        | MsgApplyOp
        | MsgCancel
        | MsgRebuild
        | MsgExportStep
        | MsgReady
        | MsgProgress
        | MsgOp
        | MsgConversationTurn
        | MsgError
        | MsgMeshFrame
        | MsgNewDoc
        | MsgOpen
        | MsgSave
        | MsgListFiles
        | MsgUndo
        | MsgRedo
        | MsgFileList
        | MsgDocument
        | MsgOpenFolder
        | MsgListDir
        | MsgOpenPart
        | MsgSavePart
        | MsgNewPart
        | MsgRenamePart
        | MsgRemovePart
        | MsgDir
    ) = Field(
        ...,
        description='Any control-message envelope on the wire (discriminated by `type`).',
        title='Message',
    )


class TouchProtocol(BaseModel):
    """
    Single source of truth for the Touch editor<->engine WebSocket protocol (ADR-0005). Domain types + control-message envelopes + the mesh binary-frame envelope. TS + pydantic bindings are generated from this file (`make codegen`).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    message: Message | None = None
